apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
  name: storagebs-post-upgrade
  namespace: {{ .Release.Namespace }}
spec:
  activeDeadlineSeconds: 900
  backoffLimit: 1
  template:
    metadata:
      name: storagebs-post-upgrade
    spec:
      containers:
      - name: storagebs-post-upgrade
        image: "{{ .Values.image.cubepaas.manager }}:{{ .Values.image.cubepaas.managerTag }}"
        imagePullPolicy: Always
        command:
        - longhorn-manager
        - post-upgrade
        - --from-version
        - 0.0.1
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      restartPolicy: OnFailure
      serviceAccountName: storagebs-service-account
